### ISSUE TITLE
create images error

### ISSUE THREAD

**Issue by DavadDi** [gonet2/snowflake#5]
> docker build -t snowflake .
> Sending build context to Docker daemon 405.5 kB
> Step 1 : FROM golang:1.5
>  ---> c3d2a6307f4e
> Step 2 : MAINTAINER xtaci daniel820313@gmail.com
>  ---> Using cache
>  ---> 714da1482b86
> Step 3 : ENV GOBIN /go/bin
>  ---> Using cache
>  ---> c384540bc104
> Step 4 : COPY . /go
>  ---> Using cache
>  ---> 44ee67a0397d
> Step 5 : WORKDIR /go
>  ---> Using cache
>  ---> 771c0ede8348
> Step 6 : ENV GOPATH /go:/go/.godeps
>  ---> Using cache
>  ---> 3ca6193b9d2c
> Step 7 : RUN go install snowflake
>  ---> Running in a66f056e84de
> src/etcdclient/client.go:4:2: cannot find package "github.com/coreos/etcd/client" in any of:
>   /usr/local/go/src/github.com/coreos/etcd/client (from $GOROOT)
>   /go/src/github.com/coreos/etcd/client (from $GOPATH)
>   /go/.godeps/src/github.com/coreos/etcd/client
> src/proto/snowflake.pb.go:16:8: cannot find package "github.com/golang/protobuf/proto" in any of:
>   /usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
>   /go/src/github.com/golang/protobuf/proto (from $GOPATH)
>   /go/.godeps/src/github.com/golang/protobuf/proto
> src/etcdclient/client.go:5:2: cannot find package "github.com/gonet2/libs/nsq-logger" in any of:
>   /usr/local/go/src/github.com/gonet2/libs/nsq-logger (from $GOROOT)
>   /go/src/github.com/gonet2/libs/nsq-logger (from $GOPATH)
>   /go/.godeps/src/github.com/gonet2/libs/nsq-logger
> src/snowflake/main.go:5:2: cannot find package "github.com/gonet2/libs/statsd-pprof" in any of:
>   /usr/local/go/src/github.com/gonet2/libs/statsd-pprof (from $GOROOT)
>   /go/src/github.com/gonet2/libs/statsd-pprof (from $GOPATH)
>   /go/.godeps/src/github.com/gonet2/libs/statsd-pprof
> src/snowflake/service.go:9:2: cannot find package "golang.org/x/net/context" in any of:
>   /usr/local/go/src/golang.org/x/net/context (from $GOROOT)
>   /go/src/golang.org/x/net/context (from $GOPATH)
>   /go/.godeps/src/golang.org/x/net/context
> src/snowflake/main.go:6:2: cannot find package "google.golang.org/grpc" in any of:
>   /usr/local/go/src/google.golang.org/grpc (from $GOROOT)
>   /go/src/google.golang.org/grpc (from $GOPATH)
>   /go/.godeps/src/google.golang.org/grpc
> The command '/bin/sh -c go install snowflake' returned a non-zero code: 1

dockerfile是否需要添加安装依赖包的步骤？

**Comment by xtaci** [comment]
先解决依赖，再build

**Comment by DavadDi** [comment]
使用go get按照依赖包后基本上解决问题。后编译报错undefined: grpc.SupportPackageIsVersion2，可能和google.golang.org/grpc HEAD最新版本有关，见 https://github.com/coreos/etcd/issues/5671

**Comment by xtaci** [comment]
嗯，你可以自己改改，etcd接口v3/v2现在是否需要区分。
