### ISSUE TITLE
并发请求时容易出现大面积延迟

### ISSUE THREAD

**Issue by 0x5143** [gonet2/snowflake#6]
自己实测时，同时调用800次Next接口，会出现大量的request timeout

**Comment by 0x5143** [comment]
在etcd的set操作时会出现大量的以下错误：
101: Compare failed ([33595592 != 33595593]) [33595593]
综上，这个服务的性能感觉有点问题。

我这边可能会考虑使用redis来代替，验证一下实际效果如何。
或者大家有更好的替代方案么？

**Comment by xtaci** [comment]
强一致性的分布式设计不会有太高的性能。

**Comment by 0x5143** [comment]
好吧，已经替换掉这个服务结点。
